# Generated by Django 5.0.2 on 2024-02-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapp',
            old_name='phone',
            new_name='phn_number',
        ),
    ]
