# Generated by Django 5.0.2 on 2024-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0002_rename_phone_myapp_phn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='phn_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
